services:
  - type: web
    name: tiendagamer
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          name: tiendagamer
          type: web
          property: port
